language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libcpufreq-dev libconfig8-dev
script:
- mkdir build && cd build && cmake -DNO_X86_ADAPT=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
