language: c
sudo: required
before_install:
  - bash tests/prepare_new_libconfig_for_travis.sh
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libcpufreq-dev
  - sudo apt-get install -y -qq libconfig8-dev -t xenial
script:
  - git clone https://github.com/tud-zih-energy/x86_adapt.git
  - cd x86_adapt && mkdir build && cd build && cmake -DNO_KERNEL_DRIVER=On .. && cmake --build . && cd ../..
  - PWDX=`pwd` && mkdir build && cd build && cmake -DNO_X86_ADAPT=yes -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
  - cd ../tests && ./test.sh travis
